rly_file = "North_London_Line.rly"
ttb_files = [ "NLL_MoFri_2023.ttb",]
img_files = [ "North_London_Line.bmp",]
doc_files = [ "README.md",]
release_date = "2022-03-05"
version = "1.0.0"
country_code = "GB"
factual = true
description = "Representation of the North London, West London & Gospel Oak to Barking Lines operated by London Overground"
display_name = "North London Line"
name = "North London Line"
author = "Krizar"
contributors = []
year = 2023
signal_position = "left"
